import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GetStaticProps } from 'next'
export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next </title>
                <meta name='description' content='Generated by create next app' />
                {/* <link rel='icon' href='/favicon.ico' /> */}
                <link
                    rel='icon'
                    href='https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/google/298/blueberries_1fad0.png'
                />
            </Head>
            <h1>Hello Next</h1>
        </div>
    )
}

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: {},
    }
}
